runs:
  using: composite
  steps:
    - name: Test where HOME is
      run: echo $HOME
    - name: Run make develop
      run: |
        source venv/bin/activate
        make develop
      shell: bash -l -v -e -u -o pipefail {0}
    - name: Register Mapbox Token
      run: |
        if [ ! -d $HOME/.streamlit ] ; then
            mkdir $HOME/.streamlit
        fi
        MAPBOX_TOKEN=$(curl -sS https://data.streamlit.io/tokens.json | jq -r '.["mapbox-localhost"]') \
        && echo '[mapbox]' >  ~/.streamlit/config.toml \
        && echo 'token = "'$MAPBOX_TOKEN'"' >> ~/.streamlit/config.toml
      shell: bash -l -v -e -u -o pipefail {0}
    - name: Register Streamlit User
      run: |
        echo '[general]' >  ~/.streamlit/credentials.toml
        echo 'email = "test@streamlit.io"' >> ~/.streamlit/credentials.toml
      shell: bash -l -v -e -u -o pipefail {0}