name: Test Python Versions

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash -ileo pipefail {0}
    
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.7.12", "3.10.0"]
    
    steps:
      - name: Checkout Streamlit code
        uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - uses: ./.github/actions/update_submodules
      - uses: ./.github/actions/pre_cache
      - uses: ./.github/actions/pre_make
      - uses: ./.github/actions/make_init
      - uses: ./.github/actions/make_develop
      - name: Run Linters
        run: |
          # Run eslint as a standalone command to generate the test report.
          PRE_COMMIT_NO_CONCURRENCY=true DISABLE=eslint pipenv run pre-commit run --show-diff-on-failure --color=always --all-files
          make jslint
      - name: Store Lint Results
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: lint_results
          path: frontend/test-reports
      - name: Run Type Checkers
        run: |
          make tstypecheck
          scripts/mypy --report
      - name: Store Type Check Results
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: type_check_results
          path: lib/test-reports
      - name: Run Python Tests
        run: |
          if [ ${{ matrix.python-version }} == 3.7.12 ]; then
            sudo apt-get install python3-pydot python3-pydot-ng graphviz
          fi
          make pycoverage
      - name: Run Integration Tests
        run: make integration-tests
      - name: CLI Smoke Tests
        run: make cli-smoke-tests